[package]
name = "day_24a"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.12"
array-init = "2.1.0"
cached = "0.55.1"
hashbrown = "0.15.4"
itertools = "0.14.0"
rand = "0.9.1"
rayon = "1.10.0"

[profile.profile]
inherits = "release"
debug = true
